---
# tasks file for sample-apache
- name: install httpd, mod_ssl and php
  ansible.builtin.yum:
    name:
      - "httpd"
      - "mod_ssl"
      - "php"
    state: present
   

- name: Start service Apache, if not started
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true



- name: allow traffic on port 80 HTTP `
  ansible.posix.firewalld:
    port: 80/tcp
    permanent: true
    state: enabled


- name: allow traffic on port 443 HTTPS
  ansible.posix.firewalld:
    port: 443/tcp
    permanent: true
    state: enabled



- name: write ip adress using jinja2
  ansible.builtin.template:
    src: templates/server_address
    dest: /var/www/html/index.html
  notify:
    - Restart apache
    




