---
- name: download from ansible-galaxy
  hosts: proxy
  roles:
   - role: /home/automation/plays/roles/geerlingguy.haproxy
     haproxy_backend_balance_method: roundrobin
     haproxy_backend_servers: >
      [
      {% for webserver in groups['webservers'] %}
      {
        "name": "{{ hostvars[webserver]['ansible_hostname'] | default(webserver) }}",
        "address": "{{ hostvars[webserver]['ansible_host'] | default(webserver) }}:80",
      }{% if not loop.last %},{% endif %}
      {% endfor %}
      ] 
     haproxy_frontend_port: 80

  tasks:
    - name: Permit traffic in port 80
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
         
  become: true
