---
- name: Start MySQL to generate initial password
  systemd:
    name: "mysqld"
    state: started

- name: Get temporary root password from MySQL log
  shell: "grep 'temporary password' /var/log/mysqld.log | tail -1 | awk '{print $NF}'"
  register: mysql_temp_password
  changed_when: false
  #no_log: true

- name: Set the MySQL temp password fact
  set_fact:
    mysql_initial_password: "{{ mysql_temp_password.stdout }}"
    #no_log: true


- name: Set root password from temporary default password
  command:
    argv:
      - mysqladmin
      - -u
      - root
      - "-p{{ mysql_initial_password }}"
      - password
      - "aaBB@@cc1122"
        #no_log: true


- name: uninstall validate password plugin
  command:
    argv:
      - mysql
      - -u
      - root
      - --password=aaBB@@cc1122
      - -e
      - UNINSTALL COMPONENT 'file://component_validate_password';




- name: Set root password from configured temporary password
  command:
    argv:
      - mysqladmin
      - --user=root
      - --password=aaBB@@cc1122
      - password
      - devops
        #no_log: true

